// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using seeker.Models;

namespace seeker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211031135042_DevTableCreated")]
    partial class DevTableCreated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("seeker.Models.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("devAbout")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("devEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("devFrom")
                        .HasColumnType("int");

                    b.Property<string>("devGitHub")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("devName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("devPhoneNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("devProject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Developer");
                });
#pragma warning restore 612, 618
        }
    }
}
